/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";
import Header from "../components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Code-一个纯前端的在线代码实时预览工具</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className="container mx-auto pb-5 min-h-fit">
        <div className="p-5 flex">
          <Link href="/pen/create">
            <a>
              <button className="flex text-white bg-blue-500 border-0 py-2 px-8 focus:outline-none hover:bg-blue-600 rounded text-lg">
                <svg
                  className="w-6 h-6 flex-none"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 6v6m0 0v6m0-6h6m-6 0H6"
                  />
                </svg>
                <span>新建代码片段</span>
              </button>
            </a>
          </Link>
        </div>
        <div className="flex flex-wrap text-slate-400">
          <div className="xl:w-1/4 md:w-1/2 p-4">
            <div className="relative flex flex-col-reverse rounded-lg p-6 bg-slate-800 highlight-white/5">
              <img
                className="h-40 rounded w-full object-cover object-center mb-6"
                src="https://dummyimage.com/720x400"
                alt="content"
              />
              <h3 className="tracking-widest text-blue-500 text-xs font-medium title-font">
                SUBTITLE
              </h3>
              <h2 className="text-lg  font-medium title-font mb-4">
                Chichen Itza
              </h2>
              <p className="leading-relaxed text-base">
                Fingerstache flexitarian street art 8-bit waistcoat. Distillery
                hexagon disrupt edison bulbche.
              </p>
            </div>
          </div>
          <div className="xl:w-1/4 md:w-1/2 p-4">
            <div className="relative flex flex-col-reverse rounded-lg p-6 bg-slate-800 highlight-white/5">
              <img
                className="h-40 rounded w-full object-cover object-center mb-6"
                src="https://dummyimage.com/721x401"
                alt="content"
              />
              <h3 className="tracking-widest text-blue-500 text-xs font-medium title-font">
                SUBTITLE
              </h3>
              <h2 className="text-lg  font-medium title-font mb-4">
                Colosseum Roma
              </h2>
              <p className="leading-relaxed text-base">
                Fingerstache flexitarian street art 8-bit waistcoat. Distillery
                hexagon disrupt edison bulbche.
              </p>
            </div>
          </div>
          <div className="xl:w-1/4 md:w-1/2 p-4">
            <div className="relative flex flex-col-reverse  rounded-lg p-6 bg-slate-800 highlight-white/5">
              <img
                className="h-40 rounded w-full object-cover object-center mb-6"
                src="https://dummyimage.com/722x402"
                alt="content"
              />
              <h3 className="tracking-widest text-blue-500 text-xs font-medium title-font">
                SUBTITLE
              </h3>
              <h2 className="text-lg  font-medium title-font mb-4">
                Great Pyramid of Giza
              </h2>
              <p className="leading-relaxed text-base">
                Fingerstache flexitarian street art 8-bit waistcoat. Distillery
                hexagon disrupt edison bulbche.
              </p>
            </div>
          </div>
          <div className="xl:w-1/4 md:w-1/2 p-4">
            <div className="relative flex flex-col-reverse  rounded-lg p-6 bg-slate-800 highlight-white/5">
              <img
                className="h-40 rounded w-full object-cover object-center mb-6"
                src="https://dummyimage.com/723x403"
                alt="content"
              />
              <h3 className="tracking-widest text-blue-500 text-xs font-medium title-font">
                SUBTITLE
              </h3>
              <h2 className="text-lg  font-medium title-font mb-4">
                San Francisco
              </h2>
              <p className="leading-relaxed text-base">
                Fingerstache flexitarian street art 8-bit waistcoat. Distillery
                hexagon disrupt edison bulbche.
              </p>
            </div>
          </div>
        </div>
      </div>
      <footer className="bg-[#181818] border-t border-gray-700 text-gray-400">
        <div className="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
          <p className="text-sm text-center sm:text-left">
            © 2022 http://code.runjs.cool —
            <a
              href="https://twitter.com/knyttneve"
              className="ml-1"
              target="_blank"
              rel="noopener noreferrer"
            >
              @maqibin
            </a>
          </p>
          <span className="sm:ml-auto sm:mt-0 mt-2 sm:w-auto w-full sm:text-left text-center  text-sm">
            欢迎关注微信公众号@JS酷
          </span>
        </div>
      </footer>
    </>
  );
}
